version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      timezone: America/Los_Angeles
      interval: daily
      time: "09:00"
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: ci
      include: scope
    open-pull-requests-limit: 10
    assignees:
      - acchiao

  - package-ecosystem: docker
    directory: /
    schedule:
      timezone: America/Los_Angeles
      interval: daily
      time: "09:00"
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: ci
      include: scope
    open-pull-requests-limit: 10
    assignees:
      - acchiao

  - package-ecosystem: gomod
    directory: /
    schedule:
      timezone: America/Los_Angeles
      interval: daily
      time: "09:00"
    labels:
      - dependencies
      - go
    commit-message:
      prefix: ci
      include: scope
    open-pull-requests-limit: 10
    assignees:
      - acchiao
